inherit_from: .rubocop_todo.yml

StringLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 80
  AllowURI: true
  URISchemes:
    - http
    - https

AllCops:
  Exclude:
    - batoto_ripper.gemspec
